#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jackett"
name = "Jackett"
description.en = "API support for your favorite torrent trackers"
description.fr = "API pour vos trackers torrent préférés"

version = "0.24.2014~ynh1"

maintainers = ["Navan Chauhan"]

[upstream]
license = "GPL-2.0"
code = "https://github.com/Jackett/Jackett"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "200M"
ram.build = "500M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jackett"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/Jackett/Jackett/releases/download/v0.24.2014/Jackett.Binaries.LinuxAMDx64.tar.gz"
    amd64.sha256 = "013cd10add8fe337f30216893c8634319448f1d571444c489108564b80433342"
    arm64.url = "https://github.com/Jackett/Jackett/releases/download/v0.24.2014/Jackett.Binaries.LinuxARM64.tar.gz"
    arm64.sha256 = "ff4f02af9d159f3b0ecee3c7987857a025ee35514bb9a259eb8fae06484431e1"
    armhf.url = "https://github.com/Jackett/Jackett/releases/download/v0.24.2014/Jackett.Binaries.LinuxARM32.tar.gz"
    armhf.sha256 = "f8fe94fee8e8bb1497e1e3b8d4938ebaf383a6c46e186bf4ac9cd079cfc952f8"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^Jackett.Binaries.LinuxAMDx64.tar.gz$"
    autoupdate.asset.arm64 = "^Jackett.Binaries.LinuxARM64.tar.gz$"
    autoupdate.asset.armhf = "^Jackett.Binaries.LinuxARM32.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 9117
