#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jackett"
name = "Jackett"
description.en = "API support for your favorite torrent trackers"
description.fr = "API pour vos trackers torrent préférés"

version = "0.24.1419~ynh1"

maintainers = ["Navan Chauhan"]

[upstream]
license = "GPL-2.0"
code = "https://github.com/Jackett/Jackett"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "200M"
ram.build = "500M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jackett"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/Jackett/Jackett/releases/download/v0.24.1419/Jackett.Binaries.LinuxAMDx64.tar.gz"
    amd64.sha256 = "c4f747de03f9e8db8b609e9833609bdcb9669df797dd23068d02049e40f0e00b"
    arm64.url = "https://github.com/Jackett/Jackett/releases/download/v0.24.1419/Jackett.Binaries.LinuxARM64.tar.gz"
    arm64.sha256 = "9b77bfa1477b57b3b062e27d4d269f75776766eb99a032d4f04e7a696c43c84d"
    armhf.url = "https://github.com/Jackett/Jackett/releases/download/v0.24.1419/Jackett.Binaries.LinuxARM32.tar.gz"
    armhf.sha256 = "55c736ed4c125484e0d456230c70e2bb995c34c8f3ca20ce0aaa7fdc9e5a330d"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^Jackett.Binaries.LinuxAMDx64.tar.gz$"
    autoupdate.asset.arm64 = "^Jackett.Binaries.LinuxARM64.tar.gz$"
    autoupdate.asset.armhf = "^Jackett.Binaries.LinuxARM32.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 9117
