#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jackett"
name = "Jackett"
description.en = "API support for your favorite torrent trackers"
description.fr = "API pour vos trackers torrent préférés"

version = "0.24.2040~ynh1"

maintainers = ["Navan Chauhan"]

[upstream]
license = "GPL-2.0"
code = "https://github.com/Jackett/Jackett"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "200M"
ram.build = "500M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jackett"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/Jackett/Jackett/releases/download/v0.24.2040/Jackett.Binaries.LinuxAMDx64.tar.gz"
    amd64.sha256 = "c14b5e5de7e0698b5cc415a63989b1d6ad3a677061cdb7dd78aa262b42c15e01"
    arm64.url = "https://github.com/Jackett/Jackett/releases/download/v0.24.2040/Jackett.Binaries.LinuxARM64.tar.gz"
    arm64.sha256 = "ead504eea66c5bd246f09897dd37cee692075757fdca465ed80081f4038adc23"
    armhf.url = "https://github.com/Jackett/Jackett/releases/download/v0.24.2040/Jackett.Binaries.LinuxARM32.tar.gz"
    armhf.sha256 = "30122957f6beecb93f26c80e2f96a59681fe40c70eb2885a8cc2d9ec90668349"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^Jackett.Binaries.LinuxAMDx64.tar.gz$"
    autoupdate.asset.arm64 = "^Jackett.Binaries.LinuxARM64.tar.gz$"
    autoupdate.asset.armhf = "^Jackett.Binaries.LinuxARM32.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 9117
